# Generated by Django 5.0.3 on 2024-03-15 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articlegallery_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Məqalə', 'verbose_name_plural': 'Məqalələr'},
        ),
        migrations.AlterModelOptions(
            name='articlegallery',
            options={'verbose_name': 'Məqalə Şəkili', 'verbose_name_plural': 'Məqalə Şəkilləri'},
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article-image/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi'),
        ),
        migrations.AlterField(
            model_name='articlegallery',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.article', verbose_name='Məqalə'),
        ),
        migrations.AlterField(
            model_name='articlegallery',
            name='image',
            field=models.ImageField(upload_to='article-images/', verbose_name='Qalereya Şəkli'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title',)},
        ),
    ]
