# Generated by Django 5.0.3 on 2024-03-14 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
