# Generated by Django 5.0.3 on 2024-03-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
