# Generated by Django 5.0.3 on 2024-03-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='maps_link',
            field=models.TextField(null=True),
        ),
    ]
