# Generated by Django 5.0.3 on 2024-03-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_contactinfo_maps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourwork',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
