# Generated by Django 5.0.3 on 2024-03-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_rename_adress_contactinfo_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='maps_link',
            new_name='map_link',
        ),
    ]
