# Generated by Django 5.0.3 on 2024-03-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_homeabout_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
