# Generated by Django 5.0.3 on 2024-03-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_recommendedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='products_slogan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
