# Generated by Django 5.0.3 on 2024-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_staticinfo_products_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='article_pagination',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='product_pagination',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
