# Generated by Django 5.0.3 on 2024-03-15 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_staticinfo_article_pagination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messages',
            new_name='message',
        ),
    ]
