# Generated by Django 5.0.3 on 2024-03-15 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_rename_messages_contact_message'),
        ('shop', '0012_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Haqqımızda', 'verbose_name_plural': 'Haqqımızda'},
        ),
        migrations.AlterModelOptions(
            name='aboutvideo',
            options={'verbose_name': 'Haqqımızda (Video)', 'verbose_name_plural': 'Haqqımızda (Video)'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Müraciət', 'verbose_name_plural': 'Müraciətlər'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Mağaza Əlaqə Məlumatları', 'verbose_name_plural': 'Mağaza Əlaqə Məlumatları'},
        ),
        migrations.AlterModelOptions(
            name='heroslider',
            options={'verbose_name': 'Slayder', 'verbose_name_plural': 'Slayderlər'},
        ),
        migrations.AlterModelOptions(
            name='homeabout',
            options={'verbose_name': 'Haqqımızda (Ana Səhifə)', 'verbose_name_plural': 'Haqqımızda (Ana Səhifə)'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Təklif', 'verbose_name_plural': 'Təkliflər'},
        ),
        migrations.AlterModelOptions(
            name='ourwork',
            options={'verbose_name': 'İşlərimiz', 'verbose_name_plural': 'İşlərimiz'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partnyor', 'verbose_name_plural': 'Partnyorlar'},
        ),
        migrations.AlterModelOptions(
            name='recommendedproduct',
            options={'verbose_name': 'Tövsiyə Olunan Məhsul', 'verbose_name_plural': 'Tövsiyə Olunan Məhsullar'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Sosial Media Hesabları', 'verbose_name_plural': 'Sosial Media Hesabları'},
        ),
        migrations.AlterModelOptions(
            name='staticinfo',
            options={'verbose_name': 'Statik Məlumat', 'verbose_name_plural': 'Statik Məlumatlar'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Statistika', 'verbose_name_plural': 'Statistika'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Abunə', 'verbose_name_plural': 'Abunələr'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='aboutvideo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='aboutvideo',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-Poçt'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon Nömrəsi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Mövzu'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='mail',
            field=models.EmailField(max_length=100, verbose_name='E-Poçt'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='map_link',
            field=models.TextField(null=True, verbose_name='Xəritə URL'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon Nömrəsi'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=models.ImageField(upload_to='banner-images/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='description',
            field=models.TextField(verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='image',
            field=models.ImageField(upload_to='home-about/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='ourwork',
            name='description',
            field=models.TextField(verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='ourwork',
            name='image',
            field=models.ImageField(upload_to='our-work/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='ourwork',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='partners-logo/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='recommendedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='shop.product', verbose_name='Məhsul'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İnstagram URL'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkedin URL'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='tiktok',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TikTok URL'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tüitter URL'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Whatsapp URL'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Youtube URL'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='article_pagination',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Səhifədəki Məqalələrin Sayı'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='footer_logo',
            field=models.ImageField(upload_to='logo/', verbose_name='Footer Loqo'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='footer_slogan',
            field=models.TextField(verbose_name='Footer Sloqanı'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='header_logo',
            field=models.ImageField(upload_to='logo/', verbose_name='Header Loqo'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='product_pagination',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Səhifədəki Məhsulların Sayı'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='products_slogan',
            field=models.TextField(blank=True, null=True, verbose_name='Məhsullar Sloqanı'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='branches',
            field=models.IntegerField(default=0, verbose_name='Filiallar'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='diversity',
            field=models.IntegerField(default=0, verbose_name='Məhsul Çeşidliliyi'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='employees',
            field=models.IntegerField(default=0, verbose_name='Əməkdaşlar'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='year_of_operation',
            field=models.IntegerField(default=0, verbose_name='Fəaliyyət İlləri'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='mail',
            field=models.EmailField(max_length=100, verbose_name='E-Poçt'),
        ),
    ]
