# Generated by Django 5.0.3 on 2024-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_alter_about_options_alter_aboutvideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_az',
            field=models.CharField(max_length=150, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='aboutvideo',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='aboutvideo',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='aboutvideo',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='title_az',
            field=models.CharField(max_length=150, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='title_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='ourwork',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='ourwork',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='ourwork',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='footer_slogan_az',
            field=models.TextField(null=True, verbose_name='Footer Sloqanı'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='footer_slogan_en',
            field=models.TextField(null=True, verbose_name='Footer Sloqanı'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='footer_slogan_ru',
            field=models.TextField(null=True, verbose_name='Footer Sloqanı'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='products_slogan_az',
            field=models.TextField(blank=True, null=True, verbose_name='Məhsullar Sloqanı'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='products_slogan_en',
            field=models.TextField(blank=True, null=True, verbose_name='Məhsullar Sloqanı'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='products_slogan_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Məhsullar Sloqanı'),
        ),
    ]
